[package]
name = "tangle"
version = "0.1.0"
authors = ["Risto Saarelma <risto.saarelma@iki.fi>"]
description = "Extraction and execution of code embedded in otlbook"
license = "MIT OR Apache-2.0"
edition = "2018"

[dependencies]
