[package]
name = "webserver"
version = "0.1.0"
authors = ["Risto Saarelma <risto.saarelma@iki.fi>"]
description = "Otlbook web interface"
license = "MIT OR Apache-2.0"
edition = "2018"

[dependencies]
async-std = "1"
lazy_static = "1"
log = "0.4"
tide = "0.16"

base = { path = "../base" }
