[package]
name = "webserver"
version = "0.1.0"
authors = ["Risto Saarelma <risto.saarelma@iki.fi>"]
description = "Otlbook web interface"
license = "MIT OR Apache-2.0"
edition = "2018"

[dependencies]
log = "0.4"
rouille = "3"

base = { path = "../base" }
